spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tp_music?serverTimezone=Asia/Shanghai
    username: root
    password: passw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  server:
    MaxFileSize: 50MB
    MaxRequestSize: 50MB
mybatis:
  type-aliases-package: com.example.demo.domain
  mapper-locations: classpath:mapper/*.xml
picConfig:
  path:
    songListPic:
      win: file:F:/taskWorkspace/music/songListPic/
      other: file:/opt/music/songListPic/
    song:
      win: file:F:/taskWorkspace/music/song/
      other: file:/opt/music/song/
    songPic:
      win: file:F:/taskWorkspace/music/songPic/
      other: file:/opt/music/songPic/
    singerPic:
      win: file:F:/taskWorkspace/music/singerPic/
      other: file:/opt/music/singerPic/
    avatorImages:
      win: file:F:/taskWorkspace/music/avatorImages/
      other: file:/opt/music/avatorImages/
server:
  port: 9527